//! GroupMath external value-oracle: tensor-product channels and multiplicities
//! (issue #32, deliverable 2).
//!
//! Role (see `tools/README.md` matrix): GroupMath is the primary external value
//! oracle across SU(N) and B/C/D. This test consumes the gauge-free part of
//! that oracle — the product decomposition (channel labels and outer
//! multiplicities `N^c_{ab}`) generated by
//! `tools/groupmath/gen_groupmath_products.wls` via `ReduceRepProduct` — and
//! checks racah's [`racah::sun::directproduct`] / [`racah::bcd::directproduct`]
//! reproduce it exactly. GroupMath and racah share the same Dynkin node order
//! (verified in the generator header), so labels compare with no relabeling.
//!
//! The CGC *values* (GroupMath `Invariants`) are a different gauge with no
//! documented deterministic map to racah's; per the exactness contract they
//! are not compared here — that is the #29 alignment-harness job (see the
//! generator's API-reconnaissance header).
#![cfg(feature = "cgc-gen")]

use std::collections::BTreeMap;

use num_bigint::BigInt;

use racah::bcd::{directproduct as bdp, Irrep as Bcd, Series};
use racah::sun::{directproduct as sdp, Irrep as Sun};

const FIXTURES: &str = include_str!("fixtures/groupmath_products.txt");

/// A decomposition keyed by the summand's Dynkin label.
type Channels = BTreeMap<Vec<i64>, u32>;

fn csv_i64(s: &str) -> Vec<i64> {
    s.split(',').map(|x| x.trim().parse().unwrap()).collect()
}

/// Parse the `c:n c:n ...` channel field into a label→multiplicity map.
fn parse_channels(s: &str) -> Channels {
    s.split_whitespace()
        .map(|tok| {
            let (label, mult) = tok.rsplit_once(':').unwrap();
            (csv_i64(label), mult.parse().unwrap())
        })
        .collect()
}

/// racah dimensions and product channels for a group token, so both the SU(N)
/// and B/C/D pipelines feed one comparison. Returns `(dim_a, dim_b, channels)`.
fn racah_side(group: &str, a: &[i64], b: &[i64]) -> (BigInt, BigInt, Channels) {
    // B/C/D groups: (series, expected rank is implied by the label length).
    let bcd_series = match group {
        "SO5" | "SO7" => Some(Series::B),
        "SO6" => Some(Series::D),
        "Sp4" | "Sp6" => Some(Series::C),
        _ => None,
    };
    if let Some(series) = bcd_series {
        let ia = Bcd::from_dynkin(series, a).unwrap();
        let ib = Bcd::from_dynkin(series, b).unwrap();
        let ch = bdp(&ia, &ib)
            .unwrap()
            .into_iter()
            .map(|(k, v)| (k.dynkin(), v))
            .collect();
        return (ia.dim(), ib.dim(), ch);
    }
    // SU(N): the token is "SU" followed by N.
    assert!(group.starts_with("SU"), "unknown group token {group}");
    let _n: usize = group[2..].parse().unwrap();
    let ia = Sun::from_dynkin(a).unwrap();
    let ib = Sun::from_dynkin(b).unwrap();
    let ch = sdp(&ia, &ib)
        .unwrap()
        .into_iter()
        .map(|(k, v)| (k.dynkin(), v))
        .collect();
    (ia.dim(), ib.dim(), ch)
}

struct Row {
    group: String,
    a: Vec<i64>,
    b: Vec<i64>,
    dim_a: BigInt,
    dim_b: BigInt,
    channels: Channels,
}

fn parse() -> Vec<Row> {
    let mut rows = Vec::new();
    for line in FIXTURES.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with("---") || line.starts_with('#') {
            continue;
        }
        let f: Vec<&str> = line.split('|').map(str::trim).collect();
        assert_eq!(f.len(), 5, "malformed fixture line: {line}");
        let dims: Vec<&str> = f[3].split_whitespace().collect();
        rows.push(Row {
            group: f[0].to_string(),
            a: csv_i64(f[1]),
            b: csv_i64(f[2]),
            dim_a: dims[0].parse().unwrap(),
            dim_b: dims[1].parse().unwrap(),
            channels: parse_channels(f[4]),
        });
    }
    rows
}

#[test]
fn fixture_is_present_and_covers_the_battery() {
    let rows = parse();
    // Red on an empty/missing-data path (TDD): the generator must have run.
    assert!(
        rows.len() >= 20,
        "expected the full battery, got {}",
        rows.len()
    );
    let groups: std::collections::BTreeSet<_> = rows.iter().map(|r| r.group.as_str()).collect();
    for g in [
        "SU2", "SU3", "SU4", "SU5", "SO5", "SO6", "SO7", "Sp4", "Sp6",
    ] {
        assert!(groups.contains(g), "battery missing group {g}");
    }
    // The named SO6 adjoint^2 channels: the 84 = [0,2,2] and the OM=2 adjoint.
    let adj2 = rows
        .iter()
        .find(|r| r.group == "SO6" && r.a == [0, 1, 1] && r.b == [0, 1, 1])
        .expect("SO6 adjoint^2 row");
    assert_eq!(adj2.channels[&vec![0, 2, 2]], 1, "the 84 channel");
    assert_eq!(adj2.channels[&vec![0, 1, 1]], 2, "the OM=2 adjoint channel");
}

#[test]
fn racah_reproduces_groupmath_products() {
    for r in parse() {
        let (dim_a, dim_b, channels) = racah_side(&r.group, &r.a, &r.b);
        assert_eq!(dim_a, r.dim_a, "{} {:?} dim_a", r.group, r.a);
        assert_eq!(dim_b, r.dim_b, "{} {:?} dim_b", r.group, r.b);
        assert_eq!(
            channels, r.channels,
            "{} {:?} x {:?} channels disagree with GroupMath",
            r.group, r.a, r.b
        );
    }
}
