from collections.abc import Sequence

import numpy as np
from numpy.typing import NDArray

class Irrep:
    """An irreducible representation of SU(N), labelled by its Dynkin label."""

    def __init__(self, dynkin: Sequence[int]) -> None: ...
    @classmethod
    def from_weight(cls, weight: Sequence[int]) -> Irrep: ...
    @classmethod
    def trivial(cls, n: int) -> Irrep: ...
    @property
    def dynkin(self) -> list[int]: ...
    @property
    def weight(self) -> list[int]: ...
    @property
    def rank(self) -> int: ...
    def dim(self) -> int: ...
    def dual(self) -> Irrep: ...

def fusion(a: Irrep, b: Irrep) -> list[tuple[Irrep, int]]: ...
def fusion_multiplicity(a: Irrep, b: Irrep, c: Irrep) -> int: ...
def clebsch_gordan(s1: Irrep, s2: Irrep, s3: Irrep) -> NDArray[np.float64]: ...
def f_symbol(
    a: Irrep, b: Irrep, c: Irrep, d: Irrep, e: Irrep, f: Irrep
) -> NDArray[np.float64]: ...
def r_symbol(a: Irrep, b: Irrep, c: Irrep) -> NDArray[np.float64]: ...
def check_f_unitarity(a: Irrep, b: Irrep, c: Irrep, d: Irrep) -> None: ...
def check_pentagon(a: Irrep, b: Irrep, c: Irrep, d: Irrep) -> None: ...
def check_hexagon(a: Irrep, b: Irrep, c: Irrep) -> None: ...
def sun_authority_fingerprint() -> str: ...
def su2_frobenius_schur(two_j: int) -> float: ...
